### ISSUE TITLE
ReferenceError: this_startAnonymous is not defined

### ISSUE THREAD

**Issue by mihailradkov** [FusionAuth/fusionauth-node-client#6]
I'm using the latest 1.12.0 version of this client library and I'm unable to perform requests with it.

Seems that there is a typo at https://github.com/FusionAuth/fusionauth-node-client/blame/94e576fea5fa1e186165dfb8954bb738d455f5fd/lib/FusionAuthClient.js#L3501

```
ReferenceError: this_startAnonymous is not defined
    at FusionAuthClient._start (/media/mihail/Workspace1/git/cli/node_modules/@fusionauth/node-client/lib/FusionAuthClient.js:3501:5)
    at Promise (/media/mihail/Workspace1/git/cli/node_modules/@fusionauth/node-client/lib/FusionAuthClient.js:1081:12)
    at tryCallTwo (/media/mihail/Workspace1/git/cli/node_modules/promise/lib/core.js:45:5)
    at doResolve (/media/mihail/Workspace1/git/cli/node_modules/promise/lib/core.js:200:13)
    at new Promise (/media/mihail/Workspace1/git/cli/node_modules/promise/lib/core.js:66:3)
    at FusionAuthClient.importKey (/media/mihail/Workspace1/git/cli/node_modules/@fusionauth/node-client/lib/FusionAuthClient.js:1080:12)
```

`this_startAnonymous` -> `this._startAnonymous`

**Comment by robotdan** [comment]
Thanks @mihailradkov for letting us know. We'll get this fixed momentarily.

**Comment by robotdan** [comment]
Fixed, thanks!
https://www.npmjs.com/package/@fusionauth/node-client 1.12.1
